### PR TITLE
Added aria-label for search input

### PR DESCRIPTION
**Pull request by ellinge**
Added possibility to specify aria-label for search input with fallback on placeholder.

Also updated so that {search} was not left anywhere.

Added windows-support for build. Not sure what's correct though since the css seems to be available both in root and in css-folder. Both the documention html points on /css/ at least and the same cp-arguments is used so for both. But the latest css seems to be in the dist root. So I've updated it to match so that css gets put in root and /css for demo.

https://unpkg.com/browse/simple-datatables@7.0.3/dist/css/style.css
https://unpkg.com/browse/simple-datatables@7.0.3/dist/style.css (this seems to match the src/css)

### CODE REVIEW

**Comment by johanneswilm** [comment]
Thanks @ellinge ,
a lot of this looks good. As for the win32 specific changes - given that I don't know any dev using win32 and I don't know how many more times you will contribute here, I think they could be difficult to maintain over time. Is it not possible to rewrite the existing commands to also work on win32?

**Comment by ellinge** [comment]
No other dev with windows you say? 😆 One would have to install cygwin to get cp to work with windows I guess. But you can drop that part if you would like. But make sure that the CSS is outputted in one place as it seems to be distributed in two places now.

**Comment by ellinge** [comment]
https://2ality.com/2022/08/npm-package-scripts.html#file-system-operations this perhaps can be an alternative?

**Comment by johanneswilm** [comment]
yes, that looks good. I also remember there was a package called cpx or so for that purpose back when Windows was still a thing among developers.
As for css - I tried to change the location to be inside the folder a few versions ago, but it lead to problems for projects so I moved it back for the dist version.

**Comment by ellinge** [comment]
Are you joking me? The majority of developers still use Windows even if *unix/mac has m

**Comment by ellinge** [comment]
You are joking right? A lot of developers use Windows still. The majority I would say.

**Comment by johanneswilm** [comment]
sure, there are many subgroups of devs. Just noone I know. And that is important for this library as I won't be able update those scripts. Last time I had Windows on my dev machine was around 1996 when I was 16.

**Comment by ellinge** [comment]
Now this open source project should work across windows / *nix, shx seems to work fine

**Comment by johanneswilm** [comment]
super. thanks!
btw, I was looking for typical aria values related to search fields and didn't find anything directly. What kind of values would one typically use there?

**Comment by johanneswilm** [comment]
This seems to say that the type should be changed to "search" and that description maybe included, but not a label: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/searchbox_role

Is that incorrect?

**Comment by ellinge** [comment]
Do what you like. Currently it does not validate. Ensuring WCAG is not always straightforward. The best is to try to find and example case from w3c (e.g., https://w3c.github.io/aria-practices/examples/grid/dataGrids.html) but not always the case you find one. You don’t have a search form. You’re filtering table data. One could intepret it should be sufficient with a label (either by a tag or by attribute). A aria-description to tell what it filters/search perhaps could be good as well.

**Comment by johanneswilm** [comment]
@ellinge Nono, I want to do the right thing. So what would you put as aria label then? Or are there several viable options?

The important thing is that screen readers understand it correctly, right?

**Comment by ellinge** [comment]
Perhaps see how other components interpret it. Here’s one focusing on WCAG which also has search fields: https://www.ag-grid.com/javascript-data-grid/accessibility/

**Comment by johanneswilm** [comment]
@ellinge  a short survey of what others are doing:

https://datatables.net
`<input type="search" class="" placeholder="" aria-controls="example">`

https://mdbootstrap.com/docs/b4/jquery/tables/datatables/
`<input type="search" class="form-control" placeholder="Search" aria-controls="dtBasicExample">`

https://vincjo.fr/datatables/examples/basic
`<input placeholder="Search..." spellcheck="false" class="svelte-qq5up">`

**Comment by johanneswilm** [comment]
> The best is to try to find an example case from w3c (e.g., https://w3c.github.io/aria-practices/examples/grid/dataGrids.html)

Sure. But there is no search field on that page, right?

> Here’s one focusing on WCAG which also has search fields: https://www.ag-grid.com/javascript-data-grid/accessibility/

I clicked around a bunch on that site, but I couldn't find any example of a table search there either.

I'm thinking that if you are not allowed to publicly disclose what value you will be using for that aria label and we don't have any other input, then it's probably best if I just follow the common practice of other datatables on the net and use `<input type="search">` as the main configuration. That will satisfy 99.9% of usecases and in your case, you can simply override the template to use something else. 

Would that work for you @ellinge ?

**Comment by ellinge** [comment]
Sure, but you merged it anyway now?

**Comment by johanneswilm** [comment]
yes, the other things you did were really helpful. Thanks again for that!

**Comment by ellinge** [comment]
@johanneswilm Compiled from main now and tried it out, even with type="search" [WAVE](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) gives an error:
image

**Comment by ellinge** [comment]
https://dev.to/grahamthedev/placeholder-text-on-an-input-instead-of-a-label-does-it-pass-wcag-the-answer-may-surprise-you-94m#comment-1gadk here is some discussion around just this.

**Comment by ellinge** [comment]
https://www.w3.org/TR/html-aam-1.0/#input-type-text-input-type-password-input-type-number-input-type-search-input-type-tel-input-type-email-input-type-url-and-textarea-element-accessible-name-computation

**Comment by johanneswilm** [comment]
Thanks, that browser extension is very helpful. 

> So my proposal is a revisit or do I need to supply my own template?

Based on the recommendation that WAVE provides:

> How to Fix It
If a text label for a form control is visible, use the <label> element to associate it with its respective form control. If there is no visible label, either provide an associated label, add a descriptive title attribute to the form control, or reference the label(s) using aria-labelledby. Labels are not required for image, submit, reset, button, or hidden form controls.

Given that there is no visual label, we should probably add a title attribute to the input field and then make the contents of that title attribute a string that is configurable as for example `labels.searchTitle`. Do you agree?

I will make a 7.1.0 release in the not too distant future, hopefully, after fixing the last remaining bug, and this could meaningfully go into that release as well.

**Comment by ellinge** [comment]
I had a searchAriaLabel for this reason, then it does not show on hover as title does, but that's perhaps something that's wished for?

**Comment by johanneswilm** [comment]
> I had a searchAriaLabel for this reason, then it does not show on hover as title does, but that's perhaps something that's wished for? 

Yeah, I'm thinking a title on hovering can be useful for users without a screenreader who would want some extra instructions as well. I can make the default text "Search within table" or something similarly generic.

As for https://www.w3.org/WAI/tutorials/forms/instructions/ - the problem with adding a label that is not a placeholder is just that most modern websites don't want to have separate placeholders/labels as their design. In fact, that same webpage uses the placeholder as the label in search field in the top right corner for other users. So in order to follow their own guidelines they have added a `<label>` but then hide it for other users. I'm not sure that makes any technical sense. But if that is what is required to make a website accessible - Ok, then so be it.

**Pull request merged**
