### PR TITLE
find/update row feature

### PR DESCRIPTION
**Pull request by tkroll**
Feature to find & update existing rows in the data table.

Give this table:
```html
<table id="dt">
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Age</th>
  </tr>
  </thead>
  <tbody>
    <tr>
      <td>342</td>
      <td>Fred</td>
      <td>24</td>
    </tr>
    <tr>
      <td>144</td>
      <td>Mary</td>
      <td>21</td>
    </tr>
    <tr>
      <td>645</td>
      <td>Todd</td>
      <td>32</td>
    </tr>
  </tbody>
</table>
```
```javascript
const dataTable = new DataTable("#dt")
```

Can update an existing row:
```javascript
const rows = dataTable.rows()

// find row with string in first td
const {index, cols} = rows.findRow(0, '144')
// index = 1
// cols = ['144', 'Mary', '21']

// change td
cols[1] = 'Susan'

// update row in data table
rows.updateRow(index, cols)
```

### CODE REVIEW

**Review by johanneswilm — APPROVED** [review]

**Comment by johanneswilm** [comment]
@tkroll Would you want to update the documentation as well?

**Comment by tkroll** [comment]
> @tkroll Would you want to update the documentation as well?

No problemo. Will do in the next few days when I get a chance.

**Comment by Nexxkinn** [comment]
any plan to publish a new version of it? I need this feature for our project to programmatically update selected part of rows.

**Comment by johanneswilm** [comment]
@Nexxkinn yes, how about the documentation I requested above? Can you write that?

**Comment by Nexxkinn** [comment]
Sure, I'll add it when we finalize our project at the end of the year.

**Comment by tkroll** [comment]
Will take care of it this weekend. Sorry for the delay.

**Pull request merged**
