### PR TITLE
Correct row edited in dialog

### PR DESCRIPTION
**Pull request by deakjahn**
Test this but I think this is the way to get the correct row. The original solution overwrote the row and then got the index. It seems to work for me now.

### CODE REVIEW

**Comment by deakjahn** [comment]
#189

**Comment by johanneswilm** [comment]
@deakjahn That extra 1 comes from the header row. I believe the index should be correct if we replace: 

```js
this.dataTable.dom.rows[row.dataIndex]
```

with

```js
this.dataTable.body.rows[row.dataIndex]
```

**Comment by deakjahn** [comment]
Then be it so.

**Comment by deakjahn** [comment]
@johanneswilm A bit of styling classes also added to the PR.

**Comment by deakjahn** [comment]
You gave me a good idea with the other one. I always tried to use `dt.data` to access the rows but this is much better.

**Pull request merged**
