### PR TITLE
Added a few different demos

### PR DESCRIPTION
**Pull request by oneezy**
Added more demo files to `demo` folder

### CODE REVIEW

**Comment by johanneswilm** [comment]
nice!  could we also get the dependent files into the repo? For users it's unclear if they can reuse the tools functions, etc. and there is no way for me to control whether those files suddenly go down or are replaced with malicious JavaScript.

**Comment by oneezy** [comment]
are you referring to the external `.json` files form the ajax examples or something more?

**Comment by johanneswilm** [comment]
Well, I see there are CSS files loaded from other places, some JavaScript is hosted somewhere else and also a datatable-csv.txt is loaded from another server. Could we not just have all this in this repo?

**Review by oneezy — COMMENTED** [review]
I removed all external linking files from demo except the built [simple-datatables@latest](https://cdn.jsdelivr.net/npm/simple-datatables@latest) `js`

https://cdn.jsdelivr.net/npm/simple-datatables@latest

**Pull request merged**
