### PR TITLE
Add options is split query word in search

### PR DESCRIPTION
**Pull request by Cesar-1e**
isSplitQueryWord = true(default); //Search for each word
isSplitQueryWord = false; //Search for the complete word

https://github.com/fiduswriter/simple-datatables/assets/75588717/d73bd293-987e-412a-b26b-b3f376b4c75d

### CODE REVIEW

**Comment by johanneswilm** [comment]
Hey @Cesar-1e , thanks for your contribution.

Notice though that we support multiple search inputs. So it cannot be a global option. It needs to be connected to individual search inputs (possibly as a `data-` attribute).

**Comment by Cesar-1e** [comment]
I understand, do I proceed to perform by column?
Example:

https://github.com/fiduswriter/simple-datatables/blob/745a8b6020173b82c79c0a082d1f62bf508be24c/docs/demos/10-filters/index.html#L39

```
window.dt = new window.simpleDatatables.DataTable(t,
    {
        data,
        columns: [
            {
                select: 1,
                filter: ["Assistant", "Manager"],
                isSplitQueryWord: true
            },
            {
                select: 4,
                type: "date", 
                format: "MM/DD/YYYY"
            }]
    })
```

**Comment by johanneswilm** [comment]
Hey,
yes, I think that would be a good idea.

**Comment by ge-ku** [comment]
Hello, this is an option I was just looking for!

I have a suggestion though, how about adding something like a `searchQuerySeparator`, so we can use other symbols (or multiple symbols) instead of space?

And preferably use `trim()` after splitting search query, so if query separator is "," and search string is "unity, pugh" it will search for "unity" and "pugh" instead of " pugh". Or maybe allow separator to be a regular expression, I'm not sure if it will significantly affect performance though.

Such an option should be set to space by default. Perhaps setting it to empty string could lead to proposed behavior of this pull request so it could all be one option.

**Comment by Cesar-1e** [comment]
@johanneswilm Okey!!!
In the course of this week I make the changes, since the truth is that I am super busy right now 😅😅

**Comment by Cesar-1e** [comment]
> Hello, this is an option I was just looking for!
> 
> I have a suggestion though, how about adding something like a `searchQuerySeparator`, so we can use other symbols (or multiple symbols) instead of space?
> 
> And preferably use `trim()` after splitting search query, so if query separator is "," and search string is "unity, pugh" it will search for "unity" and "pugh" instead of " pugh". Or maybe allow separator to be a regular expression, I'm not sure if it will significantly affect performance though.
> 
> Such an option should be set to space by default. Perhaps setting it to empty string could lead to proposed behavior of this pull request so it could all be one option.

@ge-ku I find it spectacular.
I consider the 'searchQuerySeparator' parameter to be global or what do you say @johanneswilm

**Comment by johanneswilm** [comment]
@Cesar-1e Yes, I think it's quite ok to have the 'searchQuerySeparator' parameter be global.

**Comment by Cesar-1e** [comment]
@johanneswilm Ready!!

- Finished `isSplitQueryWord` settings
- Implemented `searchQuerySeparator`


https://github.com/fiduswriter/simple-datatables/assets/75588717/b1d2c736-c368-43e8-8ba2-812412a9010b


https://github.com/fiduswriter/simple-datatables/assets/75588717/2e142945-9d85-4836-89b3-d01dee070273

**Comment by johanneswilm** [comment]
thanks @Cesar-1e! I will make a release shortly. After fixing one more issue.

**Pull request merged**
