### PR TITLE
Fix #2

### LINKED ISSUE #2: Sorting is offset by 1
When clicking a header to sort the column, the next column is sorted instead

### PR DESCRIPTION
**Pull request by GerwinBosch**
Fixes #2.

### CODE REVIEW

**Comment by LaurensRietveld** [comment]
@johanneswilm Do you have more info on whether this will make it into simple-datatables? Not pushing for a fast issue-response-time here, but asking because there have been little movement in this repo since the fork and I'd like to know more about this lib's status

**Comment by johanneswilm** [comment]
Sorry, somehow this escaped my inbox. I will review shortly.

**Comment by johanneswilm** [comment]
@LaurensRietveld If ypu are interested in faster response times, I'd be open to add comaintainers to this repo.

**Comment by johanneswilm** [comment]
@LaurensRietveld And as for this libs status: Currently, it is doing for me what I need it to do, so except for bugs like the one you have uncovered here which I hopefully would have found myself at some point, I am not planning on any major feature additions in the short-term.

One thing I may look at in the medium term is row grouping and hiding. I am using this for a list of files and I would want to add something like folders which will basically cover a number of rows.

But just because I don't have a use for more features doesn't mean that I am opposed to others adding these and me merging them. I would even be OK with someone taking over maintainership entirely. It was only because the previous package did not receive updates for months and features I needed urgently weren't being merged that I started this. Building data tables is not my principal interest.

**Comment by johanneswilm** [comment]
Ok, sounds like we'll be able to find some agreement on this. And possible, with time, we find someone whose raison d'être is datatables or something closely related to them who can take over here. I do try to answer quickly, but this time the github email must have been caught somewhere in the process.

As for the patch @GerwinBosch : I tried it out in our app. Interestingly, the sorting works without the patch and with the patch applied it sorts the column before the current one. My guess is that the " +1" is needed if using some config options and not if using others. These are my config options:

```
{
            searchable: true,
            paging: false,
            scrollY: "calc(100vh - 320px)",
            labels: {
                noRows: gettext("No sources registered") // Message shown when there are no search results
            },
            layout: {
                top: ""
            },
            data: {
                headings: ['','&emsp;&emsp;', gettext("Title"), gettext("Sourcetype"), gettext("Author"), gettext("Published"), ''],
                data: ids.map(id => this.createTableRow(id))
            },
            columns: [
                {
                    select: 0,
                    hidden: true
                },
                {
                    select: [1,6],
                    sortable: false
                }
            ]
        }
```

I hope that helps in improving the patch.

**Comment by LaurensRietveld** [comment]
Thanks Johannes, we'll take a look

**Comment by GerwinBosch** [comment]
@johanneswilm In your config you hide the first column (which is empty assuming from the header) while we didn't.
The `Colums()` object contains **all** the headings (hidden or not hidden), therefore it selected the wrong header the sort function was called. The plus one works if you only have the first column hidden, hiding the first two columns would reverse the effect described in #2. 
I've changed the selector from `activeHeadings` to `headings`. This should resolve the issue

**Comment by johanneswilm** [comment]
Yes, this also works here. I'll merge and make a patch version release.

**Pull request merged**
